repos:
  - repo: local
    hooks:
      - id: check-requirements-updated
        name: Check if requirements.txt needs update
        entry: bash -c 'echo "Remember to update requirements.txt if you added new imports!" && exit 0'
        language: system
        files: '\.py$'
        pass_filenames: false