services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
    env_file:
      - ./backend/.env.production
    command: python run_prod.py

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    environment:
      - REACT_APP_ENVIRONMENT=production
    env_file:
      - ./frontend/.env.production